# Generated by Django 5.1.1 on 2024-09-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_postmodels_postmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
